add_newline = true

# [palettes]

[character]
success_symbol = "[ ➜](bold green)"
error_symbol = "[ ➜](bold red)"

[username]
show_always = true
style_root = 'bold red'
style_user = 'bold cyan'
format = '[$user]($style)@ '
